### ISSUE TITLE
Vagrant package repo/ppa

### ISSUE THREAD

**Issue by leth** [hashicorp/vagrant-installers#12]
It'd be great if there were a package repo I could add to my system so that vagrant updates would happen automagically.

Obviously not an urgent requirement ;)
Keep up the good work!

**Comment by timmclean** [comment]
+1

**Comment by deimosfr** [comment]
+1

**Comment by asm0dey** [comment]
:+1:

**Comment by gboddin** [comment]
+1

**Comment by m-uh** [comment]
+1

**Comment by gruzzilkin** [comment]
+1

**Comment by kmoser77** [comment]
+1

**Comment by stalet** [comment]
+1

**Comment by gboddin** [comment]
Okay so :

https://gist.github.com/gboddin/d3fa7e386868a0862b81

Apt source line :

deb http://oraw.waro.be/vagrant deb main

Not signed, so you know :) 

The mentioned script is ran everyday at midnight, so you get daily updates

regards,

**Comment by alexanderadam** [comment]
@gboddin cool stuff! :+1: 

(although an official repo would be ideal of course) :wink:

**Comment by thedrow** [comment]
That's an improvement but still. hashicorp uses bintray which **already provides** debian repositories.

**Comment by gboddin** [comment]
Yeah well, considering the amount of +1, let's assume they just don't care about making their product widely available.

That's okay, I just did it to ease the life of the devs working with it, but for me Vagrant is now depcrecated, slow, and not community focused (let's say dead).

Make a proper source code, it'll build wherever you want, the fact that it needs that kind of hacks says it all for me. 

Period.

**Comment by stalet** [comment]
Thanks @gboddin :)

**Comment by mitchellh** [comment]
@gboddin You're welcome to that opinion, and I'm glad you found value out of Vagrant while you could! 

We don't base our roadmap on "+1"s and the count is not a good indicator of features that are necessary vs. features that are nice. What is necessary is fixing bugs wherever possible, improving platform support (host, guest, hypervisor), and adding features that the _community_ requests. Note our very active and long CHANGELOG: https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md

Distribution isn't Vagrant's priority right now, in that you're correct. Our downloads per month are still growing at a staggering rate, so distribution clearly isn't a short term problem. But stability, platform support, and specific features are. 

The reason this issue is still open is because we intend to do it one day, but work is prioritized based on immediate need vs. time issue is opened or "+1 count".

So for the remainder of folks in this issue who have decided that Vagrant is still useful despite the fact we don't provide a proper Debian repo, thank you, your patience is appreciated, and we continue to work towards making Vagrant the best it can be with important bug fixes and improvements.

**Comment by thedrow** [comment]
@mitchellh  Isn't this issue a low hanging fruit since you already use bitry which provides debian repositories?

**Comment by gboddin** [comment]
I think it's an important features, being able to be up to date with the latest version and with security fixes, also :

If you make distribution without that FPM thingy wide available, you'll get more developer involved with the project, for ... fixing bugs, improvements.

Also your download per month would growth with a repo. Most of the time, I discard solutions not providing update facilities, if there's another one covering the need.

I might be the only one, but so you know where your beardy linux users might be hidding ;)

Btw, I gave the code to generate a generic repo, all you need now is to sign it with your own gpg key when you make a new release ;) (and tell people to trust that gpg key in APT).

**Comment by CarlFK** [comment]
@gboddin Thank you for your efforts, and I'm sorry the powers that be aren't taking advantage of what you have provided.

@mitchellh Your post bothers me.  I think you have done nothing but be annoying.  
"Distribution isn't Vagrant's priority"  did you really think any of us couldn't figure that out?  
"we intend to do it one day" is empty words given this issue has been open for 3 years.  
"distribution clearly isn't a short term problem" is simply wrong, and you are being rude to the group of people here saying "it is a problem."    

"community requests"  - what does that mean?

**Comment by ivan-kolmychek** [comment]
@mitchellh if this issue, comments in it and all of the "+1" do not qualify as a community request, please, tell me, __what will qualify as such__?

**Comment by gboddin** [comment]
@ivan-kolmychek  Run OSX ;)

**Comment by ivan-kolmychek** [comment]
@gboddin I personaly have no problems with obtaining fresh vagrant version, [as I said before](https://github.com/mitchellh/vagrant-installers/issues/12#issuecomment-57512842), but now I'm interested - what exactly is considered "ommunity request". Before @mitchellh comment I was quite sure, that github issue with alot of followers qualifies as one. =)

**Comment by gboddin** [comment]
I think the difficulty of providing a correct source package is what's holding them back.

Also, I have the feeling that Vagrant is most widely used by OSX users/developpers. 

One plus the other makes it easy to deny this issue with non-sense terminology ("like community requests", blah ...).

I'll translate this issue once and for all :

"We don't know how source package should be handled and/or we made a design mistake at the beginning that we don't want to fix it right now because of linux users complaining"

Again, all you neeed @mitchellh (considering you don't want your package to comply to ubuntu/debian policies) is to take the code I gave you, drop it on a server and fucking sign the repo. It'll just deliver the debs you're currently providing and keep everyone up to date.

Whatever ...

**Comment by troyready** [comment]
Guys, this is out of hand and inappropriate. Yes, this is low hanging fruit and a nice benefit for devs on debian-family systems. No, that does not make the attitudes presented here appropriate.

That said, it would be nice to get this issue resolved. It seems like bintray would be the best option for this, since it (as others have mentioned) is already being used for the packages. Is there some way we can help test/implement this?

**Comment by gboddin** [comment]
@troyready 

I don't know about bintray but :

- Or bintray is like debian/ubuntu and require source-packages to build a repo
- Or vagrant's team doesn't want to click the checkbox

Does that summarize our frustration enough (especially when people say the same thing than you over and over again without any result for 2 full years, and without any return from @mitchellh  on the why is it so hard to do it at bintray) ?

I'm really confuzzled on how an almost-devops software has so much trouble with that, especially when there are solutions providen ...

**Comment by thedrow** [comment]
@gboddin As far as I can tell from their documentation they don't require source packages.

**Comment by wolfgang42** [comment]
Before I saw @gboddin's post, I created my own repository. It's using a slightly different technique, and actually signs the files. There's any number of ways this can be done; my choice of tools was entirely arbitrary and dictated primarily by what I got to work first. The deb packages are downloaded from bintray and served locally; it might even be possible to set up a redirect so they're downloaded directly from bintray, though I have no idea how apt would react to that.

Instructions for adding the repository to your computer: http://vagrant-deb.linestarve.com/

This only took a couple of hours to set up, and seems to work well. It's just serving static files, so hosting it on S3 would be very easy. I intend to continue supporting this until an official repository becomes available, at which point I'll set up appropriate redirects to point there instead.

**Comment by cameronsparr** [comment]
@wolfgang42 Thank you very much! much appreciated!!

I'll also put in my +1 for an official repo :-)

**Comment by alex-solidfire** [comment]
+1

**Comment by sweiz** [comment]
+1

**Comment by netpalantir** [comment]
+1

**Comment by michaeljohn32** [comment]
+1

**Comment by digglife** [comment]
+1

**Comment by WyriHaximus** [comment]
+1 for an official repo

**Comment by infoomatic** [comment]
+1

**Comment by wordrak** [comment]
+1

**Comment by arnt** [comment]
Ubuntu 15.04 includes a package for vagrant 1.6, which should make this less pressing.

**Comment by cameronsparr** [comment]
That's more a testament to how badly this is needed, Ubuntu 15.04 has only been released this month and it's already pretty far behind (1.7.2 is the latest vagrant version vs. 1.6 on Ubuntu 15.04)

additionally, very few Ubuntu users are going to be on 15.04 since it's not LTS

**Comment by ivan-kolmychek** [comment]
@arnt this issue was opened 3 years (~ 6 releases of Ubuntu) ago and, considering how the discussion goes, it can easily stay unresolved for another few years, so, I suggest you to not hope that Ubuntu will ship an actual version for a long time - it never does. ;)

**Comment by arnt** [comment]
@ivan-kolmychek http://packages.ubuntu.com/vivid/vagrant says the currently shipping version is 1.6.5. This should be recent enough for me at least (I need vagrant-libvirt).

**Comment by ivan-kolmychek** [comment]
@arnt [v. 1.6.5 was released Sep 5, 2014](https://github.com/mitchellh/vagrant/commit/c38e17cc29f69aaea1610451333396494181a481). So, Ubuntu 15.04, which was just released, already contains more than half a year old version. That is even more interesting if you consider that half a year is a time between "regular" Ubuntu releases.

**Comment by arnt** [comment]
Ubuntu 15.04 is supposed to mostly contain packages dating from between the 14.10 freeze in late August 2014 and the 15.04 freeze in late February 2015, so that sounds reasonable enough. Unless Vagrant changed significantly between September 2014 and February 2015?

**Comment by DavidJFelix** [comment]
+1. If you're already building a deb, a signed PPA isn't that much to ask for is it?

**Comment by Pelid** [comment]
+1

**Comment by arnt** [comment]
Actually a PPA can be quite a bit more work than a .deb. For example, you cannot take liberties with versions and dependencies when you build for a PPA, since the actual building is done on Canonical's servers.

I've no idea what the concrete problem is with Vagrant though.

**Comment by hackel** [comment]
The Vagrant team doesn't want (or doesn't have the resources) to make quality packages that adhere to the Debian Policy Manual, they'd rather produce the hack-job we see today.  Honestly, I think a better solution would be for the Vagrant team to *stop* releasing binary packages of any kind, just like most other projects.  Then the distributions will all package their own properly, and hopefully a team of kind volunteers will step up to maintain a PPA with more recent versions (based on the existing Debian/Ubuntu package), as people already have here on this thread.

**Comment by DavidJFelix** [comment]
Ppa won't need to adhere to debían policy and I think is most people's minimum expectation.

**Comment by wolfgang42** [comment]
@hackel: I'd point out that the people here on this thread who are maintaining a PPA have *not* made `quality packages that adhere to the Debian Policy Manual`. Instead, we've simply stuck a wrapper repository around the Vagrant team's very own "hack-job packages", to allow `apt` do the job it was intended for: updating packages automatically.

The feasibility of this has been proven, as evidenced by the two independent setups (@gboddin's http://oraw.waro.be/vagrant and my own http://vagrant-deb.linestarve.com, both of which were set up with a minimum of effort), and all we're waiting for at this point is for the Vagrant team to take our code, spend an hour or two setting it up with S3, and put a link to the resulting repository on the downloads page.

**Comment by arnt** [comment]
@wolfgang42 I'm curious. There are ubuntu packages that comply with the entire policy manual. Why did you based your repo around the hack rather than on Canonical's build scripts from its compliant packages? (I understand that some people may like the hack better than what the debian policy says, but you sound as if you prefer the compliant packages, hence the question.)

**Comment by gboddin** [comment]
@arnt The are no ubuntu packages that comply with the entire policy manual.

**Comment by hackel** [comment]
@gboddin What problems are there with https://packages.debian.org/experimental/vagrant ?
(They're not Canonical's build scripts, BTW! They were made by Laurent Bigonville and Antonio Terceiro.)
@wolfgang42 I am aware of that, and that is a shame.  Basing any Vagrant repo/PPA off of the package I linked above would be ideal.

The /opt/vagrant/embedded directory should *not* exist, and really bothers me.  It's 115M of duplicated dependencies!  This is why we need proper Debian packages that use system-installed dependencies.  Notice that the package I linked to is only 332.6 kB as opposed to 67.3 MB for the crappy package released by the Vagrant team.

**Comment by gboddin** [comment]
@hackel 
This is what's wrong :

https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=vagrant;dist=unstable 

And I expect the list to be incomplete.

**Comment by hackel** [comment]
@gboddin I'm not seeing any policy violation issues here, am I not seeing something?  Of course packages will occasionally have bugs that need to be fixed.  It sounds like the Vagrant team, while producing an excellent product, didn't have a clue about software distribution or package management, and so initially made their code tightly coupled to their own packaging scheme, causing many of these issues.  These issues need to be corrected.

The Debian 1.7.2 package is working quite well for me on Ubuntu 14.10 so far.

**Comment by gboddin** [comment]
@hackel Awesome them.

I don't know the heart of Vagrant, dev implication on such things made be switch product anyway, but here for eg, I can see minified jquery stuff (just reading the list of bugs). Debian has a jquery package to it have to be used.

To whoever started this package, it seems they did a good job decoupling Vagrant. I would say good luck keeping the otherwise hard-deps in sync with what's available in Debian repo's :')

Tips to anyone wanting to contrib to debian packages :

sudo apt-get install devscripts
dget http://http.debian.net/debian/pool/main/v/vagrant/vagrant_1.7.2+dfsg-2.dsc

Will checkout the package skel and prepare the build-dir.

**Comment by wolfgang42** [comment]
@arnt: I had several goals in mind:

Partly it was because, much as I prefer compliant packages, I've never actually figured out how to build one. (The Debian package-building system is, IMHO, far too complex. Arch packages can do almost everything that .deb packages can, and they're far simpler to build.)

The main reason, though, was that I was trying to build something that the Vagrant team could get behind and begin using with a minumum of effort. The current packaging system doesn't provide a properly built source package, and it doesn't seem likely that they'll get one in the near future. However, they're already building the packages, and putting them in a repo is three commands, to be run at the end of the build:
```bash
aptly repo add vagrant-deb .
aptly snapshot create vagrant-$VERSION from repo vagrant-deb
aptly publish snapshot -gpg-key=$GPG_KEY vagrant-$VERSION
```
I'm not sure how to make it any less difficult than that.

In addition, the packages in my repo are the ones on the Vagrant download page, which makes filing bugs against Vagrant simpler: the bug report can say "this bug is reproducible with the .deb package from the Vagrant download page" rather than "this bug is reproducible with some random .deb package that someone built."

**Comment by troyready** [comment]
+1 for the great explanation and practicality @wolfgang42

**Comment by gboddin** [comment]
@wolfgang42 

Thanks to you I now have to spend time checking what that aptly thing can do !

Not cool man ! 

( thanks in disguise ;) )

**Comment by gboddin** [comment]
To anyone it concerns, I'm dropping/deleting the "deb http://oraw.waro.be/vagrant deb main" repository ;)

Regards,

**Comment by imtiaz-rahi** [comment]
+1 for proper package repo

**Comment by beckybeq** [comment]
+1

**Comment by bibz** [comment]
+1

**Comment by jvrmaia** [comment]
+1

**Comment by hackel** [comment]
(I apologise to all for this message in advance!)

Please refrain from adding "+1" comments to this or ANY other bug report.  There is a "Subscribe" option which allows your interest to be registered, keeps you updated with new comments, and doesn't spam the rest of us  with your interest.  This is extremely poor Github etiquette and frankly quite rude.

@jvrmaia @bibz @beckybeq @imtiaz-rahi @Pelid @wordrak @infoomatic @WyriHaximus @digglife @michaeljohn32 @netpalantir @sweiz @alex-solidfire @stalet @kmoser77 @gruzzilkin @emdantrim @gboddin @asm0dey @deimosfr @timmclean @jness @kop @wuxxin @ckane @alexanderadam @ihrwein @JaneZadorozhnaya @indigogoo @rmetzler @nifr @vittorius @murderface13 @AlexKushn @multik888 @ivan-kolmychek @davidkarlsen @benjaminoakes @cerquide @armiller @bramwelt @DavidYKay @federkasten @balauru @pcx @demonkoryu @notapresent @rfkrocktk @daveadams @m0g @pwaller @eshao @ariddell @brendonrapp @joshuaspence @dbellettini @adymitruk @Xeoncross @1ternal @craigwatson @narkisr @i-trofimtschuk @lucaspottersky @RsrchBoy @dogmatic69 @dreamnid @number5 

I had no idea going into this, but...70+ rude devs is way over the top.  Thanks again to everyone who has actually contributed their time and effort to solving this problem, and those who have added insightful commentary.

**Comment by peterfarrell** [comment]
For those using Ansible to bootstrap local systems, feel free to use my gist that gets the latest x86_64 version of vagrant and installs it:

https://gist.github.com/peterfarrell/d55ce25612e4988c083e

Otherwise, even VirtualBox these days has an official apt repo (Yes, Oracle).

+1 (I added insightful information for those looking automate installing vagrant with ansible)

**Comment by sethvargo** [comment]
Hi all,

Thank you for all the comments. It's very clear this is something the community is interested in, but unfortunately it is not currently a high-priority item. We are going to explore packagecloud (as suggested), since none of us are super experienced in setting up or managing PPAs. While I understand that "it's easy" and we can just "follow this guide", unfortunately that is not a sustainable, long-term solution. Spending time building and maintaining that repo takes valuable development time away from the engineers who work on Vagrant. While the existing process (download and unzip) isn't very "debian-like", it does work, is easily scriptable, and gives us the flexibility of quick releases behind a CDN.

If packagecloud proves to be a viable solution, we will start publishing all our official packages there (in addition to our existing website downloads) :smile:. Thank you all for your patience regarding this issue.

**Comment by wyaeld** [comment]
@sethvargo maybe a stupid question, but does this
http://blog.bintray.com/2014/12/16/hosting-debian-packages-on-bintray-rocks/
not actually work for some reason related to the fpm packaging?

**Comment by gboddin** [comment]
Nop , it's not

**Comment by tjbenator** [comment]
+1

**Comment by gordon-morehouse** [comment]
For anybody who scrolled to the bottom, http://vagrant-deb.linestarve.com/ is the only unofficial repo that still appears to be up. Yes, this is still broken, if you want proper updates on Debian family systems you'll need to trust @wolfgang42.

**Comment by berezovskyi** [comment]
At the time of writing, Ubuntu 14.04 LTS ships with Vagrant 1.7.2 which doesn't recognize Virtualbox 5 as a valid provider (fixed in 1.7.4). The cleanest way to work around this problem is to install Virtualbox 4.3 from [officilal repositories](https://www.virtualbox.org/wiki/Linux_Downloads), which still resolves any DKMS module problems found in the Ubuntu virtualbox packages.

**Comment by artem-sidorenko** [comment]
In case somebody wants to integrate the [new releases api](https://twitter.com/mitchellh/status/661238762270126080) for populating own repos , it works for me like this:
```bash
curl -s https://releases.hashicorp.com/vagrant/index.json | jq --raw-output '.versions | to_entries | max_by(.key) | .value.builds | .[] | select(.arch=="x86_64") | select(.os=="debian") | .url '
```

**Comment by daveadams** [comment]
Very nice, @artem-sidorenko. I'm looking at other Hashicorp projects and I see that Consul has a release candidate for a future version out, which comes up in your query as the top result. So I added a filter step (the `with_entries` line) to get rid of anything matching `/-rc[0-9]+$`. Possibly there's a safer way to match, but in any case:

    curl -s https://releases.hashicorp.com/vagrant/index.json \
        | jq --raw-output \
            '.versions
            | with_entries(select(.key | test("-rc[0-9]+$") | not))
            | to_entries
            | max_by(.key)
            | .value.builds[]
            | select(.arch=="x86_64")
            | select(.os=="debian")
            | .url'

**Comment by wolfgang42** [comment]
@artem-sidorenko Thanks! I've just [updated my repo](https://github.com/wolfgang42/vagrant-deb/commit/e8e1ec04744ae6b90baf50495b0a3b390361524a) to use the new API.

With this API it also becomes very easy to add other Hashicorp projects to the repository; I've filed wolfgang42/vagrant-deb#3 and will get around to it eventually if someone doesn't beat me to it.

**Comment by teohhanhui** [comment]
http://vagrant-deb.linestarve.com is currently down... Any reason why HashiCorp wouldn't just provide an official repository?

**Comment by wolfgang42** [comment]
@teohhanhui http://vagrant-deb.linestarve.com is back up again. My entire web server was down, Apache apparently didn't come back up after an upgrade.

Check @sethvargo's  [comment above](https://github.com/mitchellh/vagrant-installers/issues/12#issuecomment-120122769) for HashiCorp's reasons for not currently providing a repository.

**Comment by pwaring** [comment]
Is there anything the community can do to help resolve this issue? The lack of a PPA means that Ubuntu users either have to use an old version of Vagrant (e.g. 1.8.1 doesn't work with Homestead) or download the latest version from the Vagrant website and then have to update manually (there doesn't seem to be an announce list for new versions either so you have to remember to check the downloads page every so often).

**Comment by ashkulz** [comment]
To co-exist with the existing infrastructure, one possibility is as follows:
- Install [reprepro](https://wiki.debian.org/SettingUpSignedAptRepositoryWithReprepro) using `sudo apt-get install -y reprepro`
- Generate signing key using `gpg2` (see [guide from DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-use-reprepro-for-a-secure-package-repository-on-ubuntu-14-04) which has separate master and signing keys)
- Run the script below with the `.deb` files in the current directory (need to change the key IDs to values generated in above step).
- transfer the `debian/` directory to the CDN.

```bash
#!/bin/bash

SIGNING_KEY="12345678"
PUBLIC_KEY="1234567890123456789012345678901234567890"
KEYSERVER="keyserver.ubuntu.com"
REPO_URL="https://releases.hashicorp.com/debian"

rm -fr debian/
mkdir -p debian/conf
echo ask-passphrase > debian/conf/options
cat > debian/conf/distributions <<END
Codename: hashicorp
Components: extra
Architectures: i386 amd64
SignWith: $SIGNING_KEY
END
reprepro -b debian/ includedeb hashicorp *.deb
cat > repo/setup.sh <<END
sudo apt-get install -y apt-transport-https
sudo apt-key adv --keyserver $KEYSERVER --recv $PUBLIC_KEY
echo "deb $REPO_URL hashicorp extra | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt-get update
END
rm -fr debian/conf debian/db
```

Someone above posted a guide with `aptly`, but I find `reprepro` easier to use when you simply have to create a repository from `.deb` packages generated by `fpm`. Either way, I do hope *some* solution gets implemented...

**Comment by artem-sidorenko** [comment]
@ashkulz you can turn existing debs to apt repository even [without any special tools (almost)](https://www.sidorenko.io/blog/2015/05/19/easy-creation-of-a-simple-apt-repo/)

The point is that this issue is not on the high-priority list :-(

**Comment by wolfgang42** [comment]
Coincident (mostly) with the release of Vagrant 2.0, I've completely rewritten the code behind [vagrant-deb.linestarve.com](https://vagrant-deb.linestarve.com). This new version generates the repository directly from the HashiCorp releases page and provides redirects to the actual packages.
This has a number of benefits:
* Package files will be downloaded directly from HashiCorp, alleviating concerns about tampering.
* Increased integrity verification: the SHA256 in the `Packages` file comes directly from their API, and the signature of the `SHA256SUMS` file is now checked against the [HashiCorp GPG key](https://www.hashicorp.com/security/).
* I can publish every version of Vagrant, not just the ones that fit on my disk.
* I've also enabled HTTP Strict Transport Security on the domain (currently with a low max-age in case something goes wrong).

I've tested these changes fairly thoroughly, but if you have any problems please [file an issue](https://github.com/wolfgang42/vagrant-deb/issues) or send me an email so I can look into it.

**Comment by supersexy** [comment]
Still no official repo in 2019? WHY?

**Comment by asm0dey** [comment]
Because Arch linux rules the world, That's why! To be serious I still don't have nay sane ide why is it so hard to build repo.

**Comment by arnt** [comment]
FWIW I once worked at a similar company with similar problem, and this task would most likely have fallen to me. The task isn't particularly hard, but it's a thing that needs to be done, and it's a kind of thing where you need expertise in a field quite far from the usual work, or else you'll get hounded by the peanut gallery. You probably will be hounded anyway, because someone will disagree with whatever you do, but if you're not an expert those people will be factually right, and that's a problem.

Hashicorp will have no shortage of other things to do. That's how life is with opensource users.

**Comment by ashkulz** [comment]
@arnt: is it possible for you to elaborate on what the gotchas can be? I'm in a similar position for a project I maintain.

**Comment by arnt** [comment]
Making a package repo involves leaving your own code and writing something "in" debian's codebase, based on and using debian's idioms. The documentation isn't too good, as usual. Learning how to do good work in a new codebase takes time.

There may be binary choices where both alternatives have drawbacks. If so, you may assume that one of the issue reporters disagrees with whatever you do and will try to engage you in a long discussion. Deep debian expertise helps with that, but acquiring that expertise also takes a lot of time.

So this is a simple task that may be assumed to take a lot of time.

In my case we had haters. (I have an email from Richard Stallman wishing for my personal bankruptcy.) AFAICT Hashicorp doesn't struggle with that kind of crap, but I don't know you. You (@ashkulz) may have that problem, in which case I feel sorry for you. It's important that the haters aren't factually right. The customers and would-be customers mustn't hear the haters be factually right. Making newbie mistakes is a bad idea.

Further, it's acceptable to do work that benefits the free users and doesn't affect the customers. The customers don't mind that. But if the new repo introduces stability problem for existing customer sites, that's a *major* problem.

Sorry about this digression. Please send me mail if you want to continue the digression.

**Comment by asm0dey** [comment]
sidenote: you don't need deep packaging expertise if you're using tools like https://www.aptly.info/

**Comment by BassemN** [comment]
There is an updated PPA here https://launchpad.net/~tiagohillebrandt/+archive/ubuntu/vagrant

**Comment by supersexy** [comment]
@BassemN - thank you very much, but this is not "official", is it? I already have a long list of several repos for different projects that start to be abandoned because the positively engaged maintainer will go on with different things, looses interest, whatever. It is really very appreciated that people take on this and do the work of hashicorp, but I still would like to have an official repo maintained by the company that produces this software, signed with a key by that company.

Also I do not want to maintain a repo myself, for same reasons.

**Comment by arnt** [comment]
@supersexy you could send email to sales@hashicorp.com and ask for a quote, you know. It's a commercial establishment, they'll provide services for pay.

**Comment by unicell** [comment]
With the introduction of Official HashiCorp Linux Repository, this issue should've been resolved I think?

https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository

**Comment by BassemN** [comment]
@unicell vagrant is not added yet to the HashiCorp Linux Repository

**Comment by unicell** [comment]
@BassemN Seems readily available already.

```
$  apt-cache madison vagrant
   vagrant |   2.2.10-4 | https://apt.releases.hashicorp.com focal/main amd64 Packages
   vagrant |      2.2.9 | https://apt.releases.hashicorp.com focal/main amd64 Packages
```

**Comment by BassemN** [comment]
@unicell thank you :+1:
